edition = "2024"
max_widthedition = "2024"
max_width = 100
fn_call_width = 80
attr_fn_like_width = 80
struct_lit_width = 50
struct_variant_width = 50
chain_width = 80
tab_spaces = 4
hard_tabs = false
fn_params_layout = "Compressed"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
brace_style = "SameLineWhere"
where_single_line = true
match_arm_blocks = true
match_block_trailing_comma = true
wrap_comments = true
comment_width = 100
normalize_comments = true
use_small_heuristics = "Max"
trailing_semicolon = true
trailing_comma = "Vertical"
reorder_imports = true
reorder_modules = true
force_multiline_blocks = false
overflow_delimited_expr = true